package com.wavefront.common.bloomfilter;

import com.google.common.annotations.VisibleForTesting;
import com.google.common.base.Objects;
import com.google.common.base.Predicate;
import com.google.common.hash.Funnel;
import com.google.common.primitives.SignedBytes;
import com.google.common.primitives.UnsignedBytes;

import javax.annotation.CheckReturnValue;
import javax.annotation.Nullable;
import javax.annotation.concurrent.ThreadSafe;
import java.io.*;

import static com.google.common.base.Preconditions.checkArgument;
import static com.google.common.base.Preconditions.checkNotNull;

/**
 * A Bloom filter for byte arrays. A Bloom filter offers an approximate containment test
 * with one-sided error: if it claims that an element is contained in it, this might be in error,
 * but if it claims that an element is <i>not</i> contained in it, then this is definitely true.
 *
 * <p>If you are unfamiliar with Bloom filters, this nice <a
 * href="http://llimllib.github.com/bloomfilter-tutorial/">tutorial</a> may help you understand how
 * they work.
 *
 * <p>The false positive probability ({@code FPP}) of a Bloom filter is defined as the probability
 * that {@linkplain #mightContain(byte[])} will erroneously return {@code true} for an object that
 * has not actually been put in the {@code BloomFilter}.
 *
 * <p>Bloom filters are serializable. They also support a more compact serial representation via the
 * {@link #writeTo} and {@link #readFrom} methods. Both serialized forms will continue to be
 * supported by future versions of this library. However, serial forms generated by newer versions
 * of the code may not be readable by older versions of the code (e.g., a serialized Bloom filter
 * generated today may <i>not</i> be readable by a binary that was compiled 6 months ago).
 *
 * <p>As of Guava 23.0, this class is thread-safe and lock-free. It internally uses atomics and
 * compare-and-swap to ensure correctness when multiple threads are used to access it.
 *
 * @author Dimitris Andreou
 * @author Kevin Bourrillion
 * @since 11.0 (thread-safe since 23.0)
 */
@ThreadSafe
public final class ReadOnlyBloomFilter
        implements Predicate<byte[]>, Serializable {
    /**
     * A strategy to translate T instances, to {@code numHashFunctions} bit indexes.
     *
     * <p>Implementations should be collections of pure functions (i.e. stateless).
     */
    interface Strategy extends java.io.Serializable {
        /**
         * Queries {@code numHashFunctions} bits of the given bit array, by hashing a user element;
         * returns {@code true} if and only if all selected bits are set.
         */
        boolean mightContain(byte[] object, int numHashFunctions, LockFreeBitArray bits);

        /**
         * Identifier used to encode this strategy, when marshalled as part of a BloomFilter. Only
         * values in the [-128, 127] range are valid for the compact serial form. Non-negative values
         * are reserved for enums defined in BloomFilterStrategies; negative values are reserved for any
         * custom, stateful strategy we may define (e.g. any kind of strategy that would depend on user
         * input).
         */
        int ordinal();
    }

    /**
     * The bit set of the BloomFilter (not necessarily power of 2!)
     */
    private final LockFreeBitArray bits;

    /**
     * Number of hashes per element
     */
    private final int numHashFunctions;

    /**
     * The strategy we employ to map an element T to {@code numHashFunctions} bit indexes.
     */
    private final Strategy strategy;

    /**
     * Creates a BloomFilter.
     */
    private ReadOnlyBloomFilter(
            LockFreeBitArray bits, int numHashFunctions, Strategy strategy) {
        checkArgument(numHashFunctions > 0, "numHashFunctions (%s) must be > 0", numHashFunctions);
        checkArgument(
                numHashFunctions <= 255, "numHashFunctions (%s) must be <= 255", numHashFunctions);
        this.bits = checkNotNull(bits);
        this.numHashFunctions = numHashFunctions;
        this.strategy = checkNotNull(strategy);
    }

    /**
     * Returns {@code true} if the element <i>might</i> have been put in this Bloom filter, {@code
     * false} if this is
     * <i>definitely</i> not the case.
     */
    @CheckReturnValue
    public boolean mightContain(byte[] object) {
        return strategy.mightContain(object, numHashFunctions, bits);
    }

    /**
     * @deprecated Provided only to satisfy the {@link Predicate} interface; use {@link #mightContain}
     * instead.
     */
    @Deprecated
    @Override
    @CheckReturnValue
    public boolean apply(byte[] input) {
        return mightContain(input);
    }

    @Override
    public boolean equals(@Nullable Object object) {
        if (object == this) {
            return true;
        }
        if (object instanceof ReadOnlyBloomFilter) {
            ReadOnlyBloomFilter that = (ReadOnlyBloomFilter) object;
            return this.numHashFunctions == that.numHashFunctions
                    && this.bits.equals(that.bits)
                    && this.strategy.equals(that.strategy);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(numHashFunctions, strategy, bits);
    }

    /**
     * Creates a {@link ReadOnlyBloomFilter BloomFilter<T>} with the expected number of insertions and
     * expected false positive probability.
     *
     * <p>Note that overflowing a {@code BloomFilter} with significantly more elements than specified,
     * will result in its
     * saturation, and a sharp deterioration of its false positive probability.
     *
     * <p>It is recommended that the funnel be implemented as a Java enum. This has the benefit of
     * ensuring proper
     * serialization and deserialization, which is important since {@link #equals} also relies on
     * object identity of funnels.
     *
     * @param expectedInsertions the number of expected insertions to the constructed {@code
     *                           BloomFilter<T>}; must be positive
     * @param fpp                the desired false positive probability (must be positive and less
     *                           than 1.0)
     * @return a {@code BloomFilter}
     */
    @CheckReturnValue
    public static ReadOnlyBloomFilter create(int expectedInsertions, double fpp) {
        return create((long) expectedInsertions, fpp);
    }

    /**
     * Creates a {@link ReadOnlyBloomFilter BloomFilter<T>} with the expected number of insertions and
     * expected false positive probability.
     *
     * <p>Note that overflowing a {@code BloomFilter} with significantly more elements than specified,
     * will result in its
     * saturation, and a sharp deterioration of its false positive probability.
     *
     * @param expectedInsertions the number of expected insertions to the constructed {@code
     *                           BloomFilter<T>}; must be positive
     * @param fpp                the desired false positive probability (must be positive and less
     *                           than 1.0)
     * @return a {@code BloomFilter}
     * @since 19.0
     */
    @CheckReturnValue
    public static ReadOnlyBloomFilter create(long expectedInsertions, double fpp) {
        return create(expectedInsertions, fpp, BloomFilterStrategies.MURMUR128_MITZ_64);
    }

    @VisibleForTesting
    static ReadOnlyBloomFilter create(long expectedInsertions, double fpp, Strategy strategy) {
        checkArgument(
                expectedInsertions >= 0, "Expected insertions (%s) must be >= 0", expectedInsertions);
        checkArgument(fpp > 0.0, "False positive probability (%s) must be > 0.0", fpp);
        checkArgument(fpp < 1.0, "False positive probability (%s) must be < 1.0", fpp);
        checkNotNull(strategy);

        if (expectedInsertions == 0) {
            expectedInsertions = 1;
        }
        /*
         * TODO(user): Put a warning in the javadoc about tiny fpp values,
         * since the resulting size is proportional to -log(p), but there is not
         * much of a point after all, e.g. optimalM(1000, 0.0000000000000001) = 76680
         * which is less than 10kb. Who cares!
         */
        long numBits = optimalNumOfBits(expectedInsertions, fpp);
        int numHashFunctions = optimalNumOfHashFunctions(expectedInsertions, numBits);
        try {
            return new ReadOnlyBloomFilter(new LockFreeBitArray(numBits), numHashFunctions, strategy);
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Could not create BloomFilter of " + numBits + " bits", e);
        }
    }

    /**
     * Creates a {@link ReadOnlyBloomFilter BloomFilter<T>} with the expected number of insertions and a
     * default expected false positive probability of 3%.
     *
     * <p>Note that overflowing a {@code BloomFilter} with significantly more elements than specified,
     * will result in its
     * saturation, and a sharp deterioration of its false positive probability.
     *
     * @param expectedInsertions the number of expected insertions to the constructed {@code
     *                           BloomFilter<T>}; must be positive
     * @return a {@code BloomFilter}
     */
    @CheckReturnValue
    public static ReadOnlyBloomFilter create(int expectedInsertions) {
        return create((long) expectedInsertions);
    }

    /**
     * Creates a {@link ReadOnlyBloomFilter BloomFilter<T>} with the expected number of insertions and a
     * default expected false positive probability of 3%.
     *
     * <p>Note that overflowing a {@code BloomFilter} with significantly more elements than specified,
     * will result in its
     * saturation, and a sharp deterioration of its false positive probability.
     *
     * <p>The constructed {@code BloomFilter<T>} will be serializable if the provided {@code
     * Funnel<T>} is.
     *
     * <p>It is recommended that the funnel be implemented as a Java enum. This has the benefit of
     * ensuring proper
     * serialization and deserialization, which is important since {@link #equals} also relies on
     * object identity of funnels.
     *
     * @param expectedInsertions the number of expected insertions to the constructed {@code
     *                           BloomFilter<T>}; must be positive
     * @return a {@code BloomFilter}
     * @since 19.0
     */
    @CheckReturnValue
    public static ReadOnlyBloomFilter create(long expectedInsertions) {
        return create(expectedInsertions, 0.03); // FYI, for 3%, we always get 5 hash functions
    }

    /*
     * Cheat sheet:
     *
     * m: total bits
     * n: expected insertions
     * b: m/n, bits per insertion
     * p: expected false positive probability
     *
     * 1) Optimal k = b * ln2
     * 2) p = (1 - e ^ (-kn/m))^k
     * 3) For optimal k: p = 2 ^ (-k) ~= 0.6185^b
     * 4) For optimal k: m = -nlnp / ((ln2) ^ 2)
     */

    /**
     * Computes the optimal k (number of hashes per element inserted in Bloom filter), given the
     * expected insertions and total number of bits in the Bloom filter.
     *
     * See http://en.wikipedia.org/wiki/File:Bloom_filter_fp_probability.svg for the formula.
     *
     * @param n expected insertions (must be positive)
     * @param m total number of bits in Bloom filter (must be positive)
     */
    @VisibleForTesting
    static int optimalNumOfHashFunctions(long n, long m) {
        // (m / n) * log(2), but avoid truncation due to division!
        return Math.max(1, (int) Math.round((double) m / n * Math.log(2)));
    }

    /**
     * Computes m (total bits of Bloom filter) which is expected to achieve, for the specified
     * expected insertions, the required false positive probability.
     *
     * See http://en.wikipedia.org/wiki/Bloom_filter#Probability_of_false_positives for the formula.
     *
     * @param n expected insertions (must be positive)
     * @param p false positive rate (must be 0 < p < 1)
     */
    @VisibleForTesting
    static long optimalNumOfBits(long n, double p) {
        if (p == 0) {
            p = Double.MIN_VALUE;
        }
        return (long) (-n * Math.log(p) / (Math.log(2) * Math.log(2)));
    }

    private Object writeReplace() {
        return new SerialForm(this);
    }

    private static class SerialForm<T> implements Serializable {
        final long[] data;
        final int numHashFunctions;
        // this field is retained for compability with guava bloomfilters.
        final Funnel<? super T> funnel;
        final Strategy strategy;


        SerialForm(ReadOnlyBloomFilter bf) {
            this.data = LockFreeBitArray.toPlainArray(bf.bits.data);
            this.numHashFunctions = bf.numHashFunctions;
            this.strategy = bf.strategy;
            this.funnel = null;
        }

        Object readResolve() {
            return new ReadOnlyBloomFilter(new LockFreeBitArray(data), numHashFunctions, strategy);
        }

        private static final long serialVersionUID = 1;
    }

    /**
     * Writes this {@code BloomFilter} to an output stream, with a custom format (not Java
     * serialization). This has been measured to save at least 400 bytes compared to regular
     * serialization.
     *
     * <p>Use {@linkplain #readFrom(InputStream)} to reconstruct the written BloomFilter.
     */
    public void writeTo(OutputStream out) throws IOException {
        /*
         * Serial form:
         * 1 signed byte for the strategy
         * 1 unsigned byte for the number of hash functions
         * 1 big endian int, the number of longs in our bitset
         * N big endian longs of our bitset
         */
        DataOutputStream dout = new DataOutputStream(out);
        dout.writeByte(SignedBytes.checkedCast(strategy.ordinal()));
        dout.writeByte(UnsignedBytes.checkedCast(numHashFunctions)); // note: checked at the c'tor
        dout.writeInt(bits.data.length());
        for (int i = 0; i < bits.data.length(); i++) {
            dout.writeLong(bits.data.get(i));
        }
    }

    /**
     * Reads a byte stream, which was written by {@linkplain #writeTo(OutputStream)}, into a {@code
     * BloomFilter<T>}.
     *
     * The {@code Funnel} to be used is not encoded in the stream, so it must be provided here.
     * <b>Warning:</b> the funnel provided <b>must</b> behave identically to the one used to populate
     * the original Bloom filter!
     *
     * @throws IOException if the InputStream throws an {@code IOException}, or if its data does not
     *                     appear to be a BloomFilter serialized using the {@linkplain
     *                     #writeTo(OutputStream)} method.
     */
    @CheckReturnValue
    public static ReadOnlyBloomFilter readFrom(InputStream in) throws IOException {
        checkNotNull(in, "InputStream");
        int strategyOrdinal = -1;
        int numHashFunctions = -1;
        int dataLength = -1;
        try {
            DataInputStream din = new DataInputStream(in);
            // currently this assumes there is no negative ordinal; will have to be updated if we
            // add non-stateless strategies (for which we've reserved negative ordinals; see
            // Strategy.ordinal()).
            strategyOrdinal = din.readByte();
            numHashFunctions = UnsignedBytes.toInt(din.readByte());
            dataLength = din.readInt();

            Strategy strategy = BloomFilterStrategies.values()[strategyOrdinal];
            long[] data = new long[dataLength];
            for (int i = 0; i < data.length; i++) {
                data[i] = din.readLong();
            }
            return new ReadOnlyBloomFilter(new LockFreeBitArray(data), numHashFunctions, strategy);
        } catch (RuntimeException e) {
            IOException ioException = new IOException(
                    "Unable to deserialize BloomFilter from InputStream."
                            + " strategyOrdinal: " + strategyOrdinal
                            + " numHashFunctions: " + numHashFunctions
                            + " dataLength: " + dataLength);
            ioException.initCause(e);
            throw ioException;
        }
    }
}
