#!/bin/bash

# Simple wrapper script for the wavefront proxy homebrew installation.

# resolve links - $0 may be a softlink                                                                               
CMD="$0"
while [ -h "$CMD" ]; do                                                                                              
  ls=`ls -ld "$CMD"`                                                                                                 
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then                                                                          
    CMD="$link"
  else 
    CMD=`dirname "$CMD"`/"$link"
  fi
done

CMDDIR=`dirname "$CMD"`                                                                                              

java -jar $CMDDIR/../lib/proxy-uber.jar "$@"
