#!/bin/bash

# Simple wrapper script for the wavefront proxy homebrew installation.

# resolve links - $0 may be a softlink                                                                               
CMD="$0"
while [ -h "$CMD" ]; do                                                                                              
  ls=`ls -ld "$CMD"`                                                                                                 
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then                                                                          
    CMD="$link"
  else 
    CMD=`dirname "$CMD"`/"$link"
  fi
done

CMDDIR=`dirname "$CMD"`                                                                                              

$CMDDIR/../lib/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j.configurationFile=$CMDDIR/../../../../etc/wavefront/wavefront-proxy/log4j2.xml -jar $CMDDIR/../lib/proxy-uber.jar "$@"
