package com.wavefront.agent.sampler;

import com.wavefront.common.MurmurHash3;
import org.junit.Test;

import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

/**
 * Tests {@link ReadOnlyAbstractWindowingBloomFilters} using a pre-built binary
 * file ({@code sharded_bloom_filters.bin}) that was generated by
 * {@code com.wavefront.common.ShardedBloomFilterFileTest}.
 *
 * The file contains 10 shards with 20 known keys inserted via
 * {@code ManagedBloomFilter}. This test deserializes the file through
 * {@link ReadOnlyAbstractWindowingBloomFilters#fromShardBytes} and verifies
 * membership queries.
 */
public class ReadOnlyAbstractWindowingBloomFiltersTest {

  private static final int MAGIC = 0x534C4246;
  private static final int FORMAT_VERSION = 1;

  private static final List<String> KNOWN_KEYS = List.of(
      "metric.cpu.usage",
      "metric.memory.free",
      "metric.disk.io",
      "metric.network.rx",
      "metric.network.tx",
      "metric.gpu.utilization",
      "metric.swap.used",
      "metric.load.1m",
      "metric.load.5m",
      "metric.load.15m",
      "ts.host.server-01",
      "ts.host.server-02",
      "ts.host.server-03",
      "ts.host.server-04",
      "ts.host.server-05",
      "ts.app.latency.p50",
      "ts.app.latency.p95",
      "ts.app.latency.p99",
      "ts.app.error.count",
      "ts.app.request.count"
  );

  private static final List<String> ABSENT_KEYS = List.of(
      "metric.nonexistent.key",
      "ts.unknown.series",
      "totally.random.string.12345",
      "another.missing.metric",
      "metric.cpu.usage.extra.suffix"
  );

  @Test
  public void testAllKnownKeysAreFound() throws IOException {
    ReadOnlyAbstractWindowingBloomFilters filters = loadFromResource();
    assertNotNull("Filters should not be null after loading valid file", filters);

    for (String key : KNOWN_KEYS) {
      byte[] keyBytes = key.getBytes(StandardCharsets.UTF_8);
      assertTrue("Expected key '" + key + "' to be found in bloom filters",
          filters.mightContain(keyBytes));
    }
  }

  @Test
  public void testAbsentKeysAreNotFound() throws IOException {
    ReadOnlyAbstractWindowingBloomFilters filters = loadFromResource();
    assertNotNull(filters);

    for (String key : ABSENT_KEYS) {
      byte[] keyBytes = key.getBytes(StandardCharsets.UTF_8);
      assertFalse("Expected key '" + key + "' to NOT be found in bloom filters",
          filters.mightContain(keyBytes));
    }
  }

  @Test
  public void testFromShardBytesReturnsNullForNullInput() throws IOException {
    assertNull(ReadOnlyAbstractWindowingBloomFilters.fromShardBytes(null, 10));
  }

  @Test
  public void testFromShardBytesReturnsNullForEmptyInput() throws IOException {
    assertNull(ReadOnlyAbstractWindowingBloomFilters.fromShardBytes(new HashMap<>(), 10));
  }

  @Test
  public void testMightContainReturnsFalseWhenShardMissing() throws IOException {
    Map<Integer, byte[]> shardBytes = loadShardBytes();
    // Keep only shard 0 — queries against keys in other shards should return false
    int keptShard = shardBytes.keySet().iterator().next();
    Map<Integer, byte[]> singleShard = new HashMap<>();
    singleShard.put(keptShard, shardBytes.get(keptShard));

    ReadOnlyAbstractWindowingBloomFilters filters =
        ReadOnlyAbstractWindowingBloomFilters.fromShardBytes(singleShard, 10);
    assertNotNull(filters);

    for (String key : KNOWN_KEYS) {
      byte[] keyBytes = key.getBytes(StandardCharsets.UTF_8);
      int shard = getShard(keyBytes, 10);
      if (shard != keptShard) {
        assertFalse("Key '" + key + "' (shard " + shard + ") should not be found when " +
            "only shard " + keptShard + " is loaded", filters.mightContain(keyBytes));
      }
    }
  }

  @Test
  public void testShardAssignmentMatchesOriginal() throws IOException {
    Map<Integer, byte[]> shardBytes = loadShardBytes();
    ReadOnlyAbstractWindowingBloomFilters filters =
        ReadOnlyAbstractWindowingBloomFilters.fromShardBytes(shardBytes, 10);
    assertNotNull(filters);

    for (String key : KNOWN_KEYS) {
      byte[] keyBytes = key.getBytes(StandardCharsets.UTF_8);
      int shard = getShard(keyBytes, 10);
      assertTrue("Shard " + shard + " should exist in the loaded data for key '" + key + "'",
          shardBytes.containsKey(shard));
    }
  }

  private static int getShard(byte[] element, int numShards) {
    return Math.abs(MurmurHash3.murmurhash3_x86_32(element, 0, element.length, 0) % numShards);
  }

  private ReadOnlyAbstractWindowingBloomFilters loadFromResource() throws IOException {
    Map<Integer, byte[]> shardBytes = loadShardBytes();
    return ReadOnlyAbstractWindowingBloomFilters.fromShardBytes(shardBytes, 10);
  }

  private Map<Integer, byte[]> loadShardBytes() throws IOException {
    try (InputStream is = getClass().getResourceAsStream("sharded_bloom_filters.bin")) {
      assertNotNull("Test resource sharded_bloom_filters.bin not found on classpath", is);
      DataInputStream dis = new DataInputStream(is);

      int magic = dis.readInt();
      if (magic != MAGIC) {
        throw new IOException("Invalid magic bytes: 0x" + Integer.toHexString(magic));
      }
      int version = dis.readInt();
      if (version != FORMAT_VERSION) {
        throw new IOException("Unsupported format version: " + version);
      }

      int totalShards = dis.readInt();
      int populatedShards = dis.readInt();

      Map<Integer, byte[]> shardBytes = new HashMap<>();
      for (int i = 0; i < populatedShards; i++) {
        int shardId = dis.readInt();
        int dataLen = dis.readInt();
        byte[] data = new byte[dataLen];
        dis.readFully(data);
        shardBytes.put(shardId, data);
      }
      return shardBytes;
    }
  }
}
