FROM mcr.microsoft.com/windows/servercore:ltsc2019

ARG SERVER_URL=https://<cluster>.wavefront.com/api
ARG API_TOKEN=API_TOKEN

ENV WAVEFRONT_URL=$SERVER_URL \
    WAVEFRONT_TOKEN=$API_TOKEN

# This script may automatically configure wavefront without prompting, based on
# these variables:
#  WAVEFRONT_URL           (required)
#  WAVEFRONT_TOKEN         (required)

# Run the agent
EXPOSE 3878
EXPOSE 2878
EXPOSE 4242

COPY proxy-installer.bat /

CMD ".\proxy-installer.bat"
