#This docker file need to be run on RHEL with subscription enabled.
FROM registry.access.redhat.com/ubi7
USER root

# This script may automatically configure wavefront without prompting, based on
# these variables:
#  WAVEFRONT_URL           (required)
#  WAVEFRONT_TOKEN         (required)
#  JAVA_HEAP_USAGE         (default is 4G)
#  WAVEFRONT_HOSTNAME      (default is the docker containers hostname)
#  WAVEFRONT_PROXY_ARGS    (default is none)
#  JAVA_ARGS               (default is none)

RUN yum-config-manager --enable rhel-7-server-optional-rpms
RUN yum update --disableplugin=subscription-manager -y && rm -rf /var/cache/yum

RUN yum install -y sudo
RUN yum install -y curl
RUN yum install -y hostname
RUN yum install -y java-11-openjdk-devel

# Add new group:user "wavefront"
RUN /usr/sbin/groupadd -g 2000 wavefront
RUN useradd --comment '' --uid 1000 --gid 2000 wavefront
RUN chown -R wavefront:wavefront /var
RUN chown -R wavefront:wavefront /usr/lib/jvm/OpenJDK-1.11.0/lib/security/cacerts
RUN chmod 755 /var

# Download wavefront proxy (latest release). Merely extract the package, don't want to try running startup scripts.
RUN curl -s https://packagecloud.io/install/repositories/wavefront/proxy/script.rpm.sh | sudo bash
RUN yum -y update
RUN yum -y -q install wavefront-proxy

# Configure agent
RUN cp /etc/wavefront/wavefront-proxy/log4j2-stdout.xml.default /etc/wavefront/wavefront-proxy/log4j2.xml

# Run the agent
EXPOSE 3878
EXPOSE 2878
EXPOSE 4242

USER 1000:2000

ADD run.sh run.sh
CMD ["/bin/bash", "/run.sh"]
