#!/bin/bash

eval $(/usr/local/bin/brew shellenv)
CMDDIR=$(dirname $0)
NAME=$(basename $0)
JAVA_HOME=$(/usr/libexec/java_home -v 11)
PROXY=$(brew --prefix $NAME)

BUFFER_DIR=${HOMEBREW_PREFIX}/var/spool/wavefront-proxy
LOG_DIR=${HOMEBREW_PREFIX}/var/log/wavefront-proxy

if [ -x ${JAVA_HOME}/bin/java ]; then
    echo "Using JAVA_HOME=${JAVA_HOME}"
else
    echo "JAVA_HOME not found"
fi

if [ ! -w ${BUFFER_DIR} ]; then 
    echo "Error!!! can't write to '${BUFFER_DIR}', please review directory permissions"
    exit -1
fi

if [ ! -w ${LOG_DIR} ]; then 
    echo "Error!!! can't write to '${LOG_DIR}', please review directory permissions"
    exit -1
fi

ENV_FILE=${HOMEBREW_PREFIX}/etc/wfproxy/prox_env.conf
if [ -f "${ENV_FILE}" ] ; then
  . ${ENV_FILE}
fi

${JAVA_HOME}/bin/java \
        $JAVA_ARGS \
        -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager \
        -Dlog4j.configurationFile=${HOMEBREW_PREFIX}/etc/wavefront/wavefront-proxy/log4j2.xml \
        -jar ${PROXY}/lib/wavefront-proxy.jar \
        -f ${HOMEBREW_PREFIX}/etc/wavefront/wavefront-proxy/wavefront.conf \
        --buffer ${BUFFER_DIR}/buffer