# NOTE: we need this to be a Dockerfile because that's the only option
# when using the Automated Build Service for Red Hat Build Partners.
# see: https://connect.redhat.com/en/blog/automated-build-service-red-hat-build-partners

FROM registry.access.redhat.com/ubi7

MAINTAINER wavefront@vmware.com

LABEL name="Wavefront Collector" \
    vendor="Wavefront by VMware" \
    version="10.13" \
    release="10.13" \
    summary="The Wavefront Proxy is a light-weight Java application that you send your metrics, histograms, and trace data to. It handles batching and transmission of your data to the Wavefront service in a secure, fast, and reliable manner." \
    description="The Wavefront Proxy is a light-weight Java application that you send your metrics, histograms, and trace data to. It handles batching and transmission of your data to the Wavefront service in a secure, fast, and reliable manner."

# Wavefront authentication can be configured in three different ways: Customers that have been
# onboarded by CSP can set up CSP api tokens or CSP OAuth apps (CSP_APP_ID, CSP_APP_SECRET).
# Customers of Wavefront can use Wavefront api token. This script may automatically
# configure Wavefront without prompting, based on these variables:
#  WAVEFRONT_URL           (required)
#  WAVEFRONT_TOKEN         (not required)
#  CSP_API_TOKEN           (not required)
#  CSP_APP_ID              (not required)
#  CSP_APP_SECRET          (not required)
#  CSP_ORG_ID              (not required)
#  JAVA_HEAP_USAGE         (default is 4G)
#  WAVEFRONT_HOSTNAME      (default is the docker containers hostname)
#  WAVEFRONT_PROXY_ARGS    (default is none)
#  JAVA_ARGS               (default is none)

RUN yum-config-manager --enable rhel-7-server-optional-rpms \
    && yum update --disableplugin=subscription-manager -y \
    && rm -rf /var/cache/yum \
    && yum install -y hostname java-11-openjdk

# Add new group:user "wavefront"
RUN groupadd -g 2000 wavefront
RUN useradd --uid 1000 --gid 2000 -m wavefront
RUN chmod a+w /usr/lib/jvm/jre/lib/security/cacerts
RUN mkdir -p /var/spool/wavefront-proxy
RUN chown -R wavefront:wavefront /var/spool/wavefront-proxy

# Run the agent
EXPOSE 3878
EXPOSE 2878
EXPOSE 4242

USER wavefront:wavefront

ADD wavefront-proxy.jar /opt/wavefront/wavefront-proxy/wavefront-proxy.jar
ADD run.sh /opt/wavefront/wavefront-proxy/run.sh
ADD log4j2.xml /etc/wavefront/wavefront-proxy/log4j2.xml
ADD LICENSE /licenses/LICENSE

CMD ["/bin/bash", "/opt/wavefront/wavefront-proxy/run.sh"]


