#!/bin/bash -e

# chkconfig: - 99 00
# description: Wavefront Proxy

### BEGIN INIT INFO
# Provides:          wavefront-proxy
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:
# Required-Stop:
### END INIT INFO

#############################
service_name="$(basename $0)"

DESC="Wavefront Proxy"
APP_NAME="wavefront-proxy"
USER="wavefront"
WAVEFRONT_DIR="/opt/$USER"
PROXY_DIR="$WAVEFRONT_DIR/wavefront-proxy"
export JAVA_HOME="$PROXY_DIR/jre"
CONF_FILE="$PROXY_DIR/conf/wavefront.conf"
LOG_FILE="/var/log/wavefront.log"
ERR_FILE=$LOG_FILE
PID_FILE="/var/run/$APP_NAME.pid"
AGENT_JAR="$PROXY_DIR/bin/wavefront-push-agent.jar"
CLASS="com.wavefront.agent.PushAgentDaemon"
ARGS="-f $CONF_FILE --buffer $PROXY_DIR/bin/buffer"

PROXY_LAUNCH_CONF="/opt/wavefront/wavefront-proxy/conf/wavefront_proxy_launch.conf"
JAVA_ARGS=""
if [[ -r $PROXY_LAUNCH_CONF ]]; then
	JAVA_ARGS=`grep -ve '[[:space:]]*#' $PROXY_LAUNCH_CONF | tr '\n' ' ' | sed -e 's/^[[:space:]]*//' | sed -e 's/[[:space:]]*$//'`
fi

# In bash, the test binary "[" insists on colon expansion. So check JAVA_ARGS a different way.
case "$JAVA_ARGS" in
	("") JAVA_ARGS="-XX:+AggressiveHeap"
esac

# Source custom settings
[[ -f "/etc/sysconfig/$service_name" ]] && . /etc/sysconfig/$service_name

JSVC=$PROXY_DIR/bin/jsvc

jsvc_exec()
{
	cd $(dirname $AGENT_JAR)
	$JSVC -user $USER -home $JAVA_HOME -cp $AGENT_JAR "$JAVA_ARGS" -outfile $LOG_FILE -errfile $ERR_FILE -pidfile $PID_FILE -wait 20 -debug $1 $CLASS $ARGS
	if [[ $? -eq 0 ]]; then
		echo "Done."
	else
		echo "There was a problem, see $ERR_FILE"
	fi
}

case "$1" in
start)
	echo "Starting $DESC"
	jsvc_exec
	# The launched nanny process will create the PID_FILE shortly.
	# Instead of blocking on that we silently succeed.
;;
status)
	if [[ -f "$PID_FILE" ]]; then
		echo "$DESC is running (PID $(cat $PID_FILE))"
	else
		echo "$DESC is not running."
		exit 3
	fi
;;
stop)
	echo "Stopping $DESC"
	jsvc_exec "-stop"
;;
restart)
	if [[ -f "$PID_FILE" ]]; then
		$0 "stop"
	fi
	$0 "start"
;;
*)
	echo "Usage: $0 {status | start | stop | restart}"
	exit 1
esac
