#!/bin/bash -e

# chkconfig: - 99 00
# description: Wavefront Proxy

### BEGIN INIT INFO
# Provides:          wavefront-proxy
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:
# Required-Stop:
### END INIT INFO

################################################################################
# File any issues here: https://github.com/wavefrontHQ/java/issues.
################################################################################

service_name=$(basename "$0")
# Source custom settings
sysconfig="/etc/sysconfig/$service_name"
# shellcheck source=/dev/null
[[ -f "$sysconfig" ]] && . $sysconfig

desc=${DESC:-Wavefront Proxy}
user="wavefront"
wavefront_dir="/opt/wavefront"
proxy_dir=${PROXY_DIR:-$wavefront_dir/wavefront-proxy}
config_dir=${CONFIG_DIR:-/etc/wavefront/wavefront-proxy}
export JAVA_HOME="$proxy_dir/proxy-jre"
conf_file=$CONF_FILE
if [[ -z $conf_file ]]; then
    legacy_config_dir=$proxy_dir/conf
    if [[ -r "$legacy_config_dir/wavefront.conf" ]]; then
        conf_file="$legacy_config_dir/wavefront.conf"
        >&2 echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        >&2 echo "WARNING: Using wavefront.conf file found in its old location ($legacy_config_dir)."
        >&2 echo "To suppress this warning message, please move wavefront.conf to $config_dir."
        >&2 echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    else
        conf_file="$config_dir/wavefront.conf"
    fi
fi
daemon_log_file=${DAEMON_LOG_FILE:-/var/log/wavefront/wavefront-daemon.log}
err_file=$log_file
pid_file=${PID_FILE:-/var/run/$service_name.pid}
agent_jar=${AGENT_JAR:-$proxy_dir/bin/wavefront-push-agent.jar}
class="com.wavefront.agent.PushAgentDaemon"
app_args=${APP_ARGS:--f $conf_file}
java_args=${JAVA_ARGS:--XX:+AggressiveHeap}

# Legacy support for overrding JVM args in wavefront_proxy_launch.conf. We don't ship this starting in 3.25,
# use /etc/sysconfig/wavefront-proxy for all configuration instead (this is a RHEL idiom, but it will work
# just as well in debian flavors).
proxy_launch_conf="/opt/wavefront/wavefront-proxy/conf/wavefront_proxy_launch.conf"
if [[ -r $proxy_launch_conf ]]; then
	replacement_java_args=$(grep -ve '[[:space:]]*#' $proxy_launch_conf | tr '\n' ' ' | sed -e 's/^[[:space:]]*//' | sed -e 's/[[:space:]]*$//')
	if [[ "$replacement_java_args" != "-XX:+AggressiveHeap" ]]; then
		>&2 echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
		>&2 echo "Using wavefront_proxy_launch.conf for JAVA_ARGS, which will override anything specified in $sysconfig."
		>&2 echo "To suppress this warning message, please specify java args in $sysconfig."
		>&2 echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
		java_args=$replacement_java_args
	fi
fi

jsvc=$proxy_dir/bin/jsvc

jsvc_exec()
{
	cd "$(dirname "$agent_jar")"
	# We want word splitting below, as we're building up a command line.
	# shellcheck disable=SC2086
	$jsvc \
		-user $user \
		-home $JAVA_HOME \
		-cp $agent_jar \
		$java_args \
		-XX:OnOutOfMemoryError="kill -1 %p" \
		-Dlog4j.configurationFile=$config_dir/log4j2.xml \
		-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager \
		-errfile $err_file \
		-pidfile $pid_file \
		-wait 20 \
		-debug \
		$1 \
		$class \
		$app_args &> $daemon_log_file
	if [[ $? -ne 0 ]]; then
		echo "There was a problem, see $err_file and $daemon_log_file"
	fi
}

case "$1" in
start)
	echo "Starting $desc"
	jsvc_exec
	echo "Done"
;;
status)
	if [[ -f "$pid_file" ]]; then
		echo "$desc is running (PID $(cat "$pid_file"))"
	else
		echo "$desc is not running."
		exit 3
	fi
;;
stop)
	echo "Stopping $desc"
	jsvc_exec "-stop"
	echo "Done"
;;
restart)
	if [[ -f "$pid_file" ]]; then
		echo "Stopping $desc"
		jsvc_exec "-stop"
	fi
	echo "Starting $desc"
	jsvc_exec
	echo "Done"
;;
*)
	echo "Usage: $0 {status | start | stop | restart}"
	exit 1
esac
