name: Sign Mac OS artifacts
on:
  workflow_dispatch:
    inputs:
      zip_name:
        description: 'Name of zip file to sign'
        required: true
jobs:
  sign_artifact:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'master'
    - name: before_install:
      run: |
        echo "received name of zip_file: ${{ github.event.inputs.zip_name }}"
        ls; pwd; pip3 install awscli; chmod +x ./macos_proxy_notarization/create_credentials.sh; ./macos_proxy_notarization/create_credentials.sh; cat ~/.aws/credentials;
